# Generated by Django 4.2.8 on 2023-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیر فعال'), ('finished', 'پایان یافته')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
