# Generated by Django 4.2.8 on 2024-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_contest_status_alter_contest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='q_count',
            field=models.IntegerField(default=3),
        ),
    ]
