# Generated by Django 4.2.8 on 2023-12-23 16:48

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import problemset.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0002_contest_status_alter_contest_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'زبان برنامه نویسی',
                'verbose_name_plural': 'زبان های برنامه نویسی',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=266)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('level', models.CharField(choices=[('easy', 'ساده'), ('moderate', 'متوسط'), ('hard', 'سخت')], max_length=8)),
                ('score', models.PositiveIntegerField(default=100)),
                ('initial_project', models.FileField(blank=True, null=True, upload_to=problemset.models.custom_upload_to)),
                ('count_of_solved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_questions', to='problemset.categories')),
                ('code_ln', models.ManyToManyField(related_name='language_questions', to='problemset.programminglanguages')),
                ('contest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='competitions.contest')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='tag_questions', to='problemset.tags')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to=problemset.models.custom_upload_to)),
                ('score', models.IntegerField(default=0)),
                ('is_checked', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('code_ln', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_answers', to='problemset.programminglanguages')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='problemset.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ارسال',
                'verbose_name_plural': 'تمامی ارسال ها',
            },
        ),
    ]
