# Generated by Django 4.2.8 on 2024-02-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_contest_status_alter_contest_duration'),
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='content',
        ),
        migrations.AddField(
            model_name='questions',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='competitions.contest'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_questions', to='problemset.tags'),
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problemset.questions')),
            ],
        ),
    ]
