# Generated by Django 4.2.8 on 2024-02-22 09:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_questions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
