# Generated by Django 4.2.8 on 2024-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_alter_questions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.CharField(choices=[('ساده', 'ساده'), ('متوسط', 'متوسط'), ('سخت', 'سخت')], max_length=8),
        ),
    ]
