# Generated by Django 4.2.8 on 2024-02-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0006_alter_questions_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-created_at'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
    ]
