# Generated by Django 4.2.8 on 2024-02-25 16:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0007_alter_questions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
